services:
  eureka:
    build: eureka
    image: staff-tracker-eureka
    networks:
      - staff-tracker

  gateway:
    build: gateway
    image: staff-tracker-gateway
    depends_on:
      - eureka
    networks:
      - staff-tracker
    ports:
      - 8080:8080

  department:
    build: department
    image: staff-tracker-department
    depends_on:
      - eureka
      - gateway
    networks:
      - staff-tracker

  database:
    image: postgres:alpine
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - staff-tracker-data:/var/lib/postgresql/data
    networks:
      - staff-tracker

networks:
  staff-tracker:

volumes:
  staff-tracker-data:
