services:
  eureka:
    build: eureka
    image: staff-tracker-eureka
    networks:
      - staff-tracker

  gateway:
    build: gateway
    image: staff-tracker-gateway
    depends_on:
      - eureka
    networks:
      - staff-tracker
    ports:
      - 8080:8080

  adminer:
    image: adminer
    restart: unless-stopped
    networks:
      - staff-tracker
    ports:
      - 8085:8080

  department:
    build: department
    image: staff-tracker-department
    environment:
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME_DEPARTMENT}
    depends_on:
      - eureka
      - gateway
    networks:
      - staff-tracker

  department-db:
    image: postgres:alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME_DEPARTMENT}
    volumes:
      - staff-tracker-department-data:/var/lib/postgresql/data
    networks:
      - staff-tracker

  employee:
    build: employee
    image: staff-tracker-employee
    environment:
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME_EMPLOYEE}
    depends_on:
      - eureka
      - gateway
    networks:
      staff-tracker:

  employee-db:
    image: postgres:alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME_EMPLOYEE}
    volumes:
      - staff-tracker-employee-data:/var/lib/postgresql/data
    networks:
      - staff-tracker

networks:
  staff-tracker:

volumes:
  staff-tracker-department-data:
  staff-tracker-employee-data:
