scrape_configs:
  - job_name: 'stafftracker'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 15s
    eureka_sd_configs:
      - server: http://eureka:8761/eureka
        refresh_interval: 30s
    relabel_configs:
      - source_labels: [ __meta_eureka_app_instance_id ]
        target_label: instance
      - source_labels: [ __meta_eureka_app_name ]
        target_label: job