spring.application.name: gateway
server.port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/

management:
  endpoints.web.exposure.include: '*'
  endpoint.health.show.details: true
