spring.application.name: eureka
server.port: 8761

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: false

management:
  endpoints.web.exposure.include: '*'
  endpoint.health.show.details: true
