spring:
  application.name: employee
  jpa:
    hibernate.ddlAuto: create-drop
  datasource:
    url: jdbc:postgresql://employee-db:5432/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driverClassName: org.postgresql.Driver
  rabbitmq:
    host: rabbitmq
    port: 5672
    user: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASSWORD}
  cloud:
    stream.bindings:
      performEmployeeDeletionBasedOnDepartment-in-0:
        destination: departmentDeletedEvents
        group: employeeConsumers

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/

management:
  endpoints.web.exposure.include: '*'
  endpoint.health.show.details: true
