spring:
  application.name: employee
  jpa:
    hibernate.ddlAuto: create-drop
  datasource:
    url: jdbc:postgresql://employee-db:5432/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driverClassName: org.postgresql.Driver

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/